spk_embed_dim: 192

flow:
  _target_: viettts.flow.flow.MaskedDiffWithXvec
  input_size: 512
  output_size: 80
  spk_embed_dim: ${spk_embed_dim}
  output_type: mel
  vocab_size: 4096
  input_frame_rate: 25
  only_mask_loss: true

  encoder:
    _target_: viettts.transformer.encoder.ConformerEncoder
    input_size: 512
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    normalize_before: true
    input_layer: linear
    pos_enc_layer_type: rel_pos_espnet
    selfattention_layer_type: rel_selfattn
    use_cnn_module: false
    macaron_style: false

  length_regulator:
    _target_: viettts.flow.length_regulator.InterpolateRegulator
    channels: 80
    sampling_ratios: [1, 1, 1, 1]

  decoder:
    _target_: viettts.flow.flow_matching.ConditionalCFM
    in_channels: 240
    n_spks: 1
    spk_emb_dim: 80
    cfm_params:
      _target_: omegaconf.DictConfig
      content:
        sigma_min: 1e-06
        solver: euler
        t_scheduler: cosine
        training_cfg_rate: 0.2
        inference_cfg_rate: 0.7
        reg_loss_type: l1

    estimator:
      _target_: viettts.flow.decoder.ConditionalDecoder
      in_channels: 320
      out_channels: 80
      channels: [256, 256]
      dropout: 0.0
      attention_head_dim: 64
      n_blocks: 4
      num_mid_blocks: 12
      num_heads: 8
      act_fn: gelu
